name: Provision Minecraft Infrastructure

# specify when it get called (triggers)
on:
  # designed to be called by an orchestration workflow
  workflow_call:
    # variables to input into the workflow
    inputs:  
      server_id:  # instance name/id
        type: string
        required: true
      instance_type: # instance type (derived from discord bot)
        type: string
        required: true
    outputs:
      server_ip:
        description: "The IP of the provisioned server"
        value: ${{ jobs.provision.outputs.server_ip }}  # look at teh provision job in the outputs section to get the ip


# jobs that happen within the workflow
jobs:
  provision:
    # runner label - ubuntu-latest lets use use the free github ubuntu runners on the latest ubuntu version
    runs-on: ubuntu-latest 
    # specify which environment to work from and get variables/secrets from
    environment: production
    # set a timeout to make sure job doesn't stall or get stuck
    timeout-minutes: 30
    # specify what ouputs are needed out of this job
    outputs:
      server_ip: ${{ steps.get_ip.outputs.server_ip }}  # look at the get_ip step in the outputs section to get the ip

    # series of steps to run within this job
    steps:
      # copy the repo to the new runner
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      # give the runner the aws credentials for this specific repo
      - name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}  # pass in specific IAM role created in AWS
          aws-region: us-east-1
          
      # install terraform on the runner
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialise Terraform backend
        run: terraform init
        working-directory: terraform

      - name: Provision infrastructure
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          TF_VAR_server_id: ${{ inputs.server_id }}
          TF_VAR_instance_type: ${{ inputs.instance_type }}
    
      - name: Get server IP from SSM
        id: get_ip
        run: |
          echo "server_ip=$(aws ssm get-parameter \
            --name "/craftform/servers/${{ inputs.server_id }}/ip" \
            --query 'Parameter.Value' \
          --output text)" >> $GITHUB_OUTPUT
      
  
